language: node_js
node_js:
  - 8
addons:
  chrome: stable

after_success:
  - yarn add codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info

before_deploy:
  - yarn build
deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_TOKEN"
  skip_cleanup: true
  on:
    branch: master

