language: node_js
node_js:
  - 8
addons:
  chrome: stable
  code_climate:
    repo_token: $CODECLIMATE

after_success: codeclimate < coverage/lcov.info

before_deploy:
  - yarn build
deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_TOKEN"
  skip_cleanup: true
  on:
    branch: master

