language: node_js
node_js:
  - 8
addons:
  chrome: stable
  firefox: latest

cache:
  directories:
  - node_modules

before_install:
  - rm -rf .git
  - git init
  - git config user.name "Travis CI"
  - git config user.email "no-reply@travis.org"
  - git add .
  - git commit -m "change updated"
  - git push --force --quiet "http://${GH_TOKEN}@${GH_REF}" master:master

before_deploy:
  - yarn build

deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_TOKEN"
  skip_cleanup: true
  on:
    branch: master

after_script:
  - yarn add codeclimate-test-reporter coveralls codecov
  - codeclimate-test-reporter < coverage/lcov.info
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - codecov

notifications:
  email: false


