language: node_js
node_js:
  - 8

script:
  - yarn build
branches:
  only:
  - master

deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_TOKEN"
  skip_cleanup: true
  on:
    branch: master

